import { describe, expect, it } from 'vitest';
import { normalizePhone } from './phone';
import { assertPublicSupabaseKey, databaseMessage } from './security';
import { applyCommand, type State } from './domain';
import { upgradeDemo } from './demo-migration';
import { projectState } from './queries';
const now=new Date('2030-01-01T08:00:00Z');
function base():State { return upgradeDemo({workshop:{id:crypto.randomUUID(),name:'Taller Prueba',phone:'',address:'',hours:'',timezone:'Europe/Madrid',appointment_minutes:60},customers:[],vehicles:[],requests:[],conversations:[],appointments:[]}); }
function receive(s:State,phone='600123456',model='León') {return applyCommand(s,{type:'intake',id:crypto.randomUUID(),data:{name:'Cliente Uno',phone,brand:'SEAT',model,plate:'1234BCD',reason:'Revisión anual',availability:'Mañanas',notes:''},messages:[{role:'user',content:'Revisión'}]},now);}
describe('Normalización y configuración segura',()=>{
 it.each(['600 123 456','+34 600 123 456','0034 600123456','(600) 123-456'])('normaliza %s',value=>expect(normalizePhone(value)).toBe('+34600123456'));
 it.each(['123','+3460012345','600123456 ext 2','34600123456','++34600123456','+1234567890123456'])('rechaza %s',value=>expect(()=>normalizePhone(value)).toThrow());
 it('acepta prefijos explícitos de otros países y exige prefijo para países sin reglas nacionales',()=>{expect(normalizePhone('+44 20 7946 0958')).toBe('+442079460958');expect(()=>normalizePhone('2079460958','GB')).toThrow('prefijo');});
 it('rechaza claves privilegiadas antes de crear el cliente',()=>{const jwt=(role:string)=>'header.'+btoa(JSON.stringify({role,iss:'supabase'}))+'.signature';expect(()=>assertPublicSupabaseKey(jwt('anon'))).not.toThrow();expect(()=>assertPublicSupabaseKey('sb_publishable_example')).not.toThrow();for(const value of [jwt('service_role'),'sb_secret_example','invalid'])expect(()=>assertPublicSupabaseKey(value)).toThrow();});
 it('oculta detalles internos de errores SQL',()=>{expect(databaseMessage({code:'23505',message:'customers_secret_constraint'})).not.toContain('constraint');expect(databaseMessage({code:'P0001',message:'Ya existe el cliente.'})).toBe('Ya existe el cliente.');});
});
describe('Reglas de la segunda iteración en demo',()=>{
 it('deduplica prefijos y corrige marca/modelo conservando vehículo',()=>{const first=receive(base());const next=receive(first,'+34 600123456','Ibiza');expect(next.customers).toHaveLength(1);expect(next.vehicles).toHaveLength(1);expect(next.vehicles[0].id).toBe(first.vehicles[0].id);expect(next.vehicles[0].model).toBe('Ibiza');expect(next.vehicles[0].version).toBe(2);});
 it('permite citas simultáneas en recursos diferentes y rechaza el mismo recurso',()=>{let s=receive(receive(base()));const first=s.resources![0];const second={...first,id:crypto.randomUUID(),name:'Elevador 2',kind:'lift' as const};s=applyCommand(s,{type:'resource',resource:second},now);const cmd={type:'appointment' as const,id:crypto.randomUUID(),request_id:s.requests[0].id,resource_id:first.id,starts_at:'2030-01-02T10:00:00Z',duration_minutes:60,notes:''};s=applyCommand(s,cmd,now);const another={...cmd,id:crypto.randomUUID(),request_id:s.requests[1].id};expect(()=>applyCommand(s,another,now)).toThrow('coincide');s=applyCommand(s,{...another,resource_id:second.id},now);expect(s.appointments).toHaveLength(2);expect(()=>applyCommand(s,{type:'resource',resource:{...first,active:false}},now)).toThrow('citas');});
 it('staff puede operar clientes pero no configuración ni recursos',()=>{const s={...base(),role:'staff' as const};expect(()=>receive(s)).not.toThrow();expect(()=>applyCommand(s,{type:'settings',workshop:s.workshop},now)).toThrow('propietario');expect(()=>applyCommand(s,{type:'resource',resource:s.resources![0]},now)).toThrow('propietario');expect(projectState({...s,audit:[{id:'a',user_id:'u',workshop_id:s.workshop.id,action:'settings',entity_type:'workshop',entity_id:s.workshop.id,created_at:now.toISOString()}]}).audit).toEqual([]);});
 it('rechaza ediciones obsoletas y registra actor y entidad al guardar',()=>{const s=receive(base());const c=s.customers[0];const next=applyCommand(s,{type:'customer',customer:{...c,name:'Nuevo nombre'}},now);expect(()=>applyCommand(next,{type:'customer',customer:c},now)).toThrow('ha cambiado');expect(next.audit?.[0]).toMatchObject({workshop_id:s.workshop.id,action:'customer',entity_id:c.id,user_id:'demo-owner'});});
 it('limita operaciones e idempotencia no consume otra operación',()=>{const s=receive(base());s.audit=Array.from({length:100},()=>({...s.audit![0],created_at:now.toISOString()}));expect(()=>applyCommand(s,{type:'status',id:s.requests[0].id,status:'pendiente'},now)).toThrow('demasiadas');expect(applyCommand(s,{type:'intake',id:s.requests[0].id,data:{} as never,messages:[]},now).requests).toHaveLength(1);});
 it('migra duplicados heredados preservando referencias y teléfonos dudosos',()=>{const s=receive(base());delete s.schema_version;const c=s.customers[0];s.customers.push({...c,id:crypto.randomUUID(),phone:'+34 600123456'});s.customers.push({...c,id:crypto.randomUUID(),phone:'123'});s.vehicles[0].customer_id=s.customers[1].id;s.requests[0].customer_id=s.customers[1].id;const next=upgradeDemo(s);expect(next.customers).toHaveLength(2);expect(next.requests[0].customer_id).toBe(next.vehicles[0].customer_id);expect(next.customers.some(c=>c.phone_e164===null)).toBe(true);expect(next.audit?.some(a=>a.action==='customer_merged')).toBe(true);});
 it('pagina raíces, conserva métricas globales y busca fuera de la primera página',()=>{const s=base();s.customers=Array.from({length:61},(_,i)=>({id:crypto.randomUUID(),workshop_id:s.workshop.id,name:'Cliente '+String(i).padStart(3,'0'),phone:'+34600123456',notes:''}));const q={view:'customers' as const,offset:0,search:'',status:'all'};const first=projectState(s,q),next=projectState(s,{...q,offset:25});expect(first.customers).toHaveLength(25);expect(first.page_info?.total).toBe(61);expect(next.customers.some(c=>first.customers.some(f=>f.id===c.id))).toBe(false);expect(projectState(s,{...q,search:'060'}).customers).toHaveLength(1);});
});
