'use client';
import type { FormEvent } from 'react';
import { ArrowRight, Bot, Check, RotateCcw, Send, Sparkles } from 'lucide-react';
import type { Command, Intake } from '@/lib/domain';
import { questions } from '@/lib/reception/provider';
import { useIntakeWizard, type IntakeSubmission } from '@/lib/reception/use-intake-wizard';
import { Field } from './ui';
const labels: Record<keyof Intake, string> = { name: 'Nombre del cliente', phone: 'Teléfono', brand: 'Marca', model: 'Modelo', plate: 'Matrícula (opcional)', reason: 'Motivo de la consulta', availability: 'Disponibilidad', notes: 'Observaciones (opcional)' };
export function Reception({ execute, onCreated }: { execute: (c: Command) => Promise<boolean>; onCreated: () => void }) {
  const onSubmit = (s: IntakeSubmission) => execute({ type: 'intake', ...s });
  const { messages, answer, setAnswer, draft, setDraft, error, busy, count, chat, send, confirm, reset } = useIntakeWizard(onSubmit);
  async function confirmAndAdvance(e: FormEvent) { if (await confirm(e)) onCreated(); }
  return <div className="reception-grid"><section className="card chat-card"><div className="chat-head"><span className="bot-icon"><Bot size={22}/></span><div><h3>Recepcionista TALLERIA</h3><span className="online"><i/>Registro manual</span></div><button className="icon-button push-right" title="Reiniciar conversación" aria-label="Reiniciar conversación" onClick={reset} disabled={busy}><RotateCcw size={18}/></button></div><div ref={chat} className="chat-messages" aria-live="polite">{messages.map((m, i) => <div className={'message ' + m.role} key={i}>{m.role === 'assistant' && <small>TALLERIA</small>}<p>{m.content}</p></div>)}</div>{!draft && <form className="chat-input" onSubmit={send}><input aria-label={questions[count]?.prompt ?? 'Respuesta'} placeholder="Escribe tu respuesta…" value={answer} onChange={e => setAnswer(e.target.value)} maxLength={2000} autoComplete="off"/><button className="button primary" aria-label="Enviar respuesta" disabled={!answer.trim()}><Send size={18}/></button></form>}<div className="chat-progress"><span>Paso {Math.min(count + 1, 8)} de 8</span><progress value={count} max={8}/></div></section><section>{draft ? <form className="card review-card" onSubmit={confirmAndAdvance}><span className="eyebrow"><Check size={14}/> LISTO PARA REVISAR</span><h2>Una conversación.<br/>Todo en orden.</h2><p className="muted">Puedes corregir los datos antes de crear la solicitud.</p><div className="form-grid">{questions.map(({ field }) => <Field key={field} label={labels[field]}>{['reason', 'notes', 'availability'].includes(field) ? <textarea rows={2} value={draft[field] ?? ''} onChange={e => setDraft({ ...draft, [field]: e.target.value })}/> : <input value={draft[field] ?? ''} onChange={e => setDraft({ ...draft, [field]: e.target.value })}/>}</Field>)}</div><button className="button primary full" disabled={busy}>{busy ? 'Creando solicitud…' : 'Confirmar y crear solicitud'}<ArrowRight size={17}/></button></form> : <div className="card reception-explainer"><span className="feature-icon"><Sparkles size={24}/></span><h2>Registra una consulta<br/>que te llegó por teléfono.</h2><p className="muted">Responde como te lo cuente el cliente. Al terminar, tendrás una solicitud lista para gestionar.</p><ol><li><b>Conversa</b><span>Nombre, vehículo, consulta y disponibilidad.</span></li><li><b>Revisa los datos</b><span>Confirma el resumen antes de guardarlo.</span></li><li><b>Gestiona la solicitud</b><span>Cliente y vehículo vinculados, listos para una cita.</span></li></ol><div className="demo-notice">Registro manual del taller, sin IA generativa. Para que tus clientes escriban directamente, comparte tu enlace de recepción digital desde Configuración.</div></div>}{error && <p className="notice error" role="alert">{error}</p>}</section></div>;
}
